// micro-frontends/vue/src/layouts/LoginLayout.vue
<template>
    <div class="vue">
        <a-button @click="goApps">login</a-button>
    </div>
</template>

<script>

export default {
    name: "LoginLayout",
    components: {

    },
    mounted() {
    },
    data() {
    },
    methods: {
        goApps() {
            this.$router.push({ path: "/apps/vue/init" });
        }
    }
};
</script>

// react-express-webpack-fullstack/src/layouts/LoginLayout.js
import React from "react";
import { push } from "react-router-redux";

export default class LoginLayout extends React.PureComponent {
    render() {
        return (
            <div>
                LoginLayout
                <button onClick={ e => { push("/apps") } }>go basicLayout</button>
            </div>
        )
    }
}
